[package]
name = "product-egui-demo"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "示例产品：构建时选定 egui 前端"

[[bin]]
name = "product-egui-demo"
path = "src/main.rs"

[dev-dependencies]
eframe = { workspace = true }
egui = { workspace = true }

[dependencies]
workbench-api = { workspace = true }
workbench-core = { workspace = true }
workbench-ui-egui = { workspace = true }
workbench-python = { workspace = true }
wb-example = { workspace = true }
env_logger = { workspace = true }
